apps/login/models.py
from apps import db, app

from apps import login_manager
from werkzeug import generate_password_hash, check_password_hash
from flask_login import UserMixin

class User(db.Model, UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(20))
    email = db.Column(db.String(30), unique=True)
    password = db.Column(db.String(128))

    def __init__(self, name, email, password):
        self.name = name
        self.email = email
        self.password = generate_password_hash(password)

    def checkpassword(self, password):
        return check_password_hash(self.password, password)

@login_manager.user_loader
def load_user(id):
    return User.query.get(int(id))

apps/login/forms.py
from flask_wtf import FlaskForm
from wtforms.validators import DataRequired, Email, Length, ValidationError, EqualTo
from wtforms import SubmitField, StringField, PasswordField
from apps.login.models import User


def email_exists(form, field):
    email = User.query.filter_by(email=field.data).first()
    if email:
        raise ValidationError('email already exists')

class regiteration(FlaskForm):
    name = StringField('enter the name', validators=[DataRequired(), Length(3,20,message='should be between 3 to 50 characters')])
    email = StringField('enter the email', validators=[DataRequired(), Email(), email_exists])
    password = PasswordField('enter the password', validators=[EqualTo('confirm', message='should be equal to password')])
    confirm = PasswordField('enter the password again', validators=[DataRequired()])
    submit = SubmitField('submit')

class loginform(FlaskForm):
    email = StringField('enter the email', validators=[DataRequired()])
    password = PasswordField('enter the password', validators=[DataRequired()])
    submit = SubmitField('submit')

apps/__init__.py
from flask import Flask
import os
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_bootstrap import Bootstrap
print('hello main')
app = Flask(__name__)


app.config['SECRET_KEY'] = 'mysecretkey'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
# app.config['SQLALCHEMY_DATABASE_URI'] = 'postgresql://postgres:Vivekshukla@123@localhost/calc'
app.config['SQLALCHEMY_DATABASE_URI'] = os.environ['DATABASE_URL']

db = SQLAlchemy(app)
bootstrap = Bootstrap(app)
Migrate(app, db)

login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = "logger.login"

from apps.login.routes import logger
app.register_blueprint(logger)

from apps.calc.routes import calculate
app.register_blueprint(calculate)

apps/calc/routes.py
from flask import Blueprint, render_template, redirect, request
from flask_login import login_required, logout_user, current_user



calculate = Blueprint('calculate', __name__)

@calculate.route('/calc', methods=['GET','POST'])
@login_required
def calc():
    if request.method == 'POST':
        var1 = request.form.get('var1', type=int)
        var2 = request.form.get('var2', type=int)
        operate = request.form.get('operation')
        if operate == 'add':
            result = var1 + var2
        elif operate == 'sub':
            result = var1 - var2
        elif operate == 'div':
             result = var1 / var2
        elif operate == 'mul':
            result = var1 * var2

        return render_template('result.html', entry=result)
    return render_template('chome.html')

apps/login/routes.py
print('above blue')
from flask_login import current_user, login_user, login_required, logout_user
print('below current_user')
from flask import Blueprint
from flask import render_template, request, url_for, flash, redirect
from apps.login.forms import regiteration, loginform
from apps.login.models import User
from apps import db

logger = Blueprint('logger', __name__)
print('below blue')



@logger.route('/')
def home():
    return render_template('home.html')

@logger.route('/register',methods=['GET', 'POST'])
def register():
    form = regiteration()
    if form.validate_on_submit():
        user = User(name=form.name.data,
                    email=form.email.data,
                    password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('registered successfully')
        return redirect (url_for('logger.login'))

    return render_template('register.html', form=form)

@logger.route('/login',methods=['GET', 'POST'])
def login():
    form = loginform()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if not user.checkpassword( form.password.data) and user is not None:
            flash('invlaid credentials')
            return redirect(url_for('logger.login'))
        login_user(user)
        return redirect(url_for('calculate.calc'))
    return render_template('login.html', form=form)

@logger.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect( url_for('logger.home'))

@logger.app_errorhandler(404)
def pagenotfound(error):
    return render_template('404.html'), 404

apps/templates/chome.html
{%extends 'layout.html'%}


{%block content%}
<div class="container">
    <form action="{{url_for('calculate.calc')}}" method="post">
        <div class="form-group">
						<label class="control-label col-xs-3" for="var_1">VARIABLE 1:</label>
						<div class="col-xs-7">
							<input type="number" class="form-control" name="var1" placeholder="&nbsp;0&nbsp;">
						</div>
					</div>
					<div class="form-group">
						<label class="control-label col-xs-3" for="var_1">VARIABLE 2:</label>
						<div class="col-xs-7">
							<input type="number" class="form-control" name="var2" placeholder="&nbsp;0&nbsp;">
						</div>
					</div>

<select class="form-select" name="operation" aria-label="Default select example">
  <option selected>Select your operation</option>
  <option value="add">ADDITION</option>
  <option value="sub">SUBTRACTION</option>
  <option value="mul">MULTIPLICSTIO</option>
    <option value="div"> DIVISION</option>
</select>
<input type="submit" value='submit'>

</form>
</div>
{%endblock%}

apps/templates/home.html
{%extends 'layout.html'%}

{%block content%}

<div class="container">
<h1>Welcome to my demo calculator</h1>
</div>
{%endblock%}

apps/templates/layout.html
{% import "bootstrap/wtf.html" as wtf %}

<html lang="en">
{#head block#}
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

</head>
<body>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{url_for('logger.home')}}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('logger.register')}}">Register</a>
        </li>
          {%if current_user.is_authenticated %}
      <li class ="nav-item">
          <a class="nav-link" href="{{url_for('logger.login')}}">Login</a>
          {%else%}
      </li>
          <li class ="nav-item">
          <a class="nav-link" href="{{url_for('logger.logout')}}">Logout</a>
         {%endif%}
          </li>

          <li class ="nav-item">
          <a class="nav-link" href="{{url_for('calculate.calc')}}">Calculate</a>

      </li>
          <li>
              <a href="">
                  {%if current_user.is_authenticated%}
                  LoggedIn as<b style="color: deeppink">{{current_user.name}}</b>
                  {%else%}
                  <b style="color: deeppink">Not LoggedIn</b>
                  {%endif%}


              </a>

          </li>
</ul>


    </div>
    </div>
</nav>

{% for message in get_flashed_messages() %}
            <div class="container alert alert-info">
                <button type="button" class="close" data-dismiss="alert"></button>
                {{ message }}
            </div>
        {% endfor %}
{%block content %}


{%endblock%}
</body>
</html>





























</html>

apps/templates/login.html
{%extends 'layout.html'%}

{%block content%}

<div class="container">
    <h3>Login</h3>
    {{form.hidden_tag()}}
    {{wtf.quick_form(form)}}



</div>


{%endblock%}

apps/templates/register.html
{%extends 'layout.html' %}

{%block content%}
<div class="container">
        <h4 style="margin-left: 45px"> Register </h4>
        <br>
          {{ form.hidden_tag() }}
          {{ wtf.quick_form(form) }}
    </div>



{%endblock%}

apps/templates/result.html
{% extends 'layout.html'%}

{%block content%}


        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4"><legend><h1>YOUR RESULT IS</h1></legend></div>
            <div class="col-md-4"></div>
        </div>
        <form class="form-horizontal">
            <fieldset disabled>
                <div class="form-group">
                    <label class="control-label col-xs-4" for="result"></label>
                    <div class="col-xs-4" align="center">
                        <input type="text" name="result" class="form-control" placeholder={{ entry}}>
                    </div>
                </div>
            </fieldset>
        </form>

{%endblock%}